### ISSUE TITLE
Crash in Keyboard handler

### ISSUE THREAD

**Issue by thesourcerer8** [pfalcon/ScratchABit#1]
File "scratchabit.py", line 506, in <module>
e.loop()
"ScratchABit/pyedit/editor.py", line 254, in loop
res = self.handle_key(key)
File "scratchabit.py", line 314, in handle_key
if '0' <= e.value[0] <= '9':
IndexError: string index out of range

**Comment by pfalcon** [comment]
Fixed. But generally, I need to know steps to reproduce an issue ;-).

**Comment by thesourcerer8** [comment]
Thanks! I was randomly typing on the keyboard ;-) (cheap fuzzing)

**Comment by pfalcon** [comment]
Well, there's definitely a lot of issues handling input and UI, I don't try to robust-ize it until I settled on UI approach and libs (so far kinda still experimenting).
