### ISSUE TITLE
CPU plugin documentation

### ISSUE THREAD

**Issue by thesourcerer8** [pfalcon/ScratchABit#29]
Please add documentation about the various CPU plugins, what they do, and what their limitations are, so that a user can know which plugin to choose.

**Comment by pfalcon** [comment]
Where would you expect to find such documentation? There's a bit of chicken and egg problem: as there's no general documentation per se, it's unclear where to make, and whether it makes sense to start, with putting random bits like that. And well, there's a starter docs, that's README. But its size can't be infinite, or people won't read it.

So, ideas are really welcome, and I of course would like to add some docs "one sweet day", but before that, in small amount of time I have, I keep adding code ;-).

**Comment by pfalcon** [comment]
And to illustrate the point that external ideas are helpful, let me show what I considered useful to do, seeing this ticket: https://github.com/pfalcon/ScratchABit/commit/9c06dfc692a5c8f1de9e17eb5a724624bfbed003 , https://github.com/pfalcon/ScratchABit/commit/abb5acc43501f75fd812411803c91d747d70ad44 .

Is that what you'd expect? No? ;-) Then I appreciate specific ideas ;-).

**Comment by pfalcon** [comment]
Also let's have https://github.com/pfalcon/ScratchABit/blob/master/plugins/cpu/README.md

**Comment by thesourcerer8** [comment]
Looks great!
