### ISSUE TITLE
Capstone may return negative addresses for arguments of jump instructions

### ISSUE THREAD

**Issue by thesourcerer8** [pfalcon/ScratchABit#34]
It seems that addresses beyond 0x80000000 are interpreted as negative numbers, even on a 64-bit python3. The address -2147360092 or -0x7ffe1d5c is actually 0x8001E2A4 which is a valid address:

./ScratchABit.py EXT0CB6Q.dec.P2.def --script import
Loading CPU plugin arm_32_capstone
Adding area: Area(0x0-0x1ffff, {'name': '.bin', 'access': 'RWX'})
Adding area: Area(0x808000-0x80ffff, {'name': '.bin', 'access': 'RWX'})
Adding area: Area(0x80000200-0x800301ff, {'name': '.bin', 'access': 'RWX'})
Loading EXT0CB6Q.dec.P21.frmw @0x0
Loading EXT0CB6Q.dec.P22.frmw @0x808000
Loading EXT0CB6Q.dec.P23.frmw @0x80000200
Processing section: entrypoints
Performing initial analysis... 3000
Traceback (most recent call last):
  File "./ScratchABit.py", line 1030, in <module>
    call_script(script)
  File "./ScratchABit.py", line 949, in call_script
    mod = __import__(script)
  File "/home/user/scratch/ScratchABit/import.py", line 2464, in <module>
    SetRegEx(0x8000855A,"T",1,2)
  File "/home/user/scratch/ScratchABit/idc.py", line 65, in SetRegEx
    engine.analyze()
  File "/home/user/scratch/ScratchABit/scratchabit/engine.py", line 947, in analyze
    if not _processor.emu():
  File "/home/user/scratch/ScratchABit/plugins/cpu/_any_capstone.py", line 176, in emu
    assert GetReg(op.addr, "T") == 0
  File "/home/user/scratch/ScratchABit/idc.py", line 28, in GetReg
    if engine.ADDRESS_SPACE.get_flags(ea, engine.AddressSpace.ALT_CODE):
  File "/home/user/scratch/ScratchABit/scratchabit/engine.py", line 245, in get_flags
    raise InvalidAddrException(addr)
scratchabit.defs.InvalidAddrException: (-2147360092, '-0x7ffe1d5c')

**Comment by pfalcon** [comment]
Weird. So far, I don't see how to reproduce this or what may be wrong, need to ponder about it.

One thing I can say is that SetRegEx() should not call engine.analyze(), it should call SetReg().

**Comment by thesourcerer8** [comment]
I guess that the problem is in ScratchABit parsing the output from Capstone, I guess that there the addresses are transferred as "int", which is signed, but should be unsigned instead. Capstone finds JUMPs (BX or something) to addresses above 0x80000000 , and somehow those addresses are interpreted as signed integers I think.

**Comment by pfalcon** [comment]
> I guess that the problem is in ScratchABit parsing the output from Capstone

Right at spot, thanks for that hint. Indeed:

~~~
  File "/mnt/hdd/projects/ScratchABit/plugins/cpu/_any_capstone.py", line 148, in ana
    assert op.value.imm >= 0, "%x %s %s" % (op.value.imm, inst.mnemonic, inst.op_str)
AssertionError: -13e11c | b #0xffec1ee4
~~~

**Comment by pfalcon** [comment]
Submitted upstream as https://github.com/aquynh/capstone/issues/1081

**Comment by pfalcon** [comment]
Worked around on the side of ScratchABit plugin in bc75f3c13f4b6bd92b1f80e1f004e726c428c556

**Comment by pfalcon** [comment]
With issue reported upstream and fixed on SABit side, closing this.

**Comment by thesourcerer8** [comment]
Hooray, it works! I was able to import a larger project successfully into ScratchABit now.
